### ISSUE TITLE
Not an issue, just a link to the explanation of EV for other visitors

### ISSUE THREAD

**Issue by kazerniel** [Lego6245/silverwastes#2]
> In short, trust the even EV, as that assumes that you have the same chance of getting a staff as you would a pair of medium gloves, while the 25% is assuming that you have the same shot at getting a piece of medium armor as you would a weapon.

https://www.reddit.com/r/Guildwars2/comments/3z11ry/ever_wondered_how_much_youd_make_by_salvaging_a/cyjg64v/

**Comment by Lego6245** [comment]
Thanks. I added some information to the table headers to help explain things. Hopefully that helps people out.
